version: '2'

services:
  web:
    build: ./go
    volumes:
      - ../:/go/src/github.com/montoias/koios-recommendations
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
    ports:
      - ${APP_PORT}:8080
    environment:
      - APP_PORT
      - GOENV
