[[constraint]]
  name = "github.com/itsjamie/gin-cors"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "github.com/ryanbradynd05/go-tmdb"
